## **`NumPy` functions**

In [1]:
import numpy as np

### **`NumPy` array Creations**

#### `.zero()` : create an array filled with *zeros*

In [2]:
array = np.zeros(5)
print(array)

[0. 0. 0. 0. 0.]


#### creating `2D` array filled with zeros

In [3]:
array = np.zeros((2,3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


#### creating `3D` array filled with zeros

In [4]:
array = np.zeros((3,3,3))
print(array)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


#### `.ones()` : create an array filled with ones

In [5]:
array = np.ones((5))
print(array)

[1. 1. 1. 1. 1.]


#### `.full()` create an array filled with the *value parameter*

#### creating `1D` array using `.full()`

In [6]:
array = np.full(5,10)
print(array)

[10 10 10 10 10]


#### creating `2D` array using `.fill()`

In [7]:
array = np.full([2,2],10)
print(array)

[[10 10]
 [10 10]]


#### `.arange()` creates a array within the given interval

In [8]:
array = np.arange(5,10)
print(array)

[5 6 7 8 9]


#### `.linspace()` creates an arrays of evenly spaced values between the given values

In [9]:
array = np.linspace(0,1,5)
print(array)

[0.   0.25 0.5  0.75 1.  ]


#### `.random.rand()` creates an array of random values between 0 and 1

In [10]:
array = np.random.rand(5)
print(array)

[0.6833847  0.31731063 0.84876984 0.70744756 0.36794183]


#### `.random.randint` creates an arrays of random integer values within the specified range

#### creating a `1D` array using `.random.randint()`

In [11]:
array = np.random.randint(0,5, size= 5)
print(array)

[3 2 3 0 2]


#### creating a `2D` array using `.random.randint()`

In [12]:
array = np.random.randint(0, 10, size= (2, 3))
print(array)

[[5 1 4]
 [4 2 5]]


#### creating a `3D` array using `.random.randint()`

In [13]:
array = np.random.randint(4,16,size=(3,3,4))
print(array)

[[[13  5 11 13]
  [11 13  9  7]
  [10  6 11  5]]

 [[11  8 10  5]
  [ 4  7 13  9]
  [13  5 12 13]]

 [[11  6  5 12]
  [12  8 15 11]
  [ 6 11  5 11]]]


In [14]:
array = np.arange(0,10,3)
print(array)

[0 3 6 9]


In [20]:
array = np.arange(4).reshape(4)
print(array)

[0 1 2 3]
