# Array ***Slicing*** in `NumPy`

In [2]:
import numpy as np

### `1D` array *Slicing*

In [3]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])

[20 30 40]


#### `Common Example`

In [4]:
print(arr[:3]) # first 3 elements
print(arr[2:]) # form index 2 to the end of an array
print(arr[ : :2]) # Every 2nd elements
print(arr[: :-1]) # Reverse the array

[10 20 30]
[30 40 50]
[10 30 50]
[50 40 30 20 10]


### `2D` array *Slicing*

#### syntax: array[**`row_start:row_stop`**, **`column_start:column_stop`**]

In [5]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr[0:2, 1:3])

[[2 3]
 [5 6]]


#### slice operator syntax: *`array[start: end: step]`*

In [6]:
print(arr[0])

[1 2 3]


In [7]:
print(arr[-1]) # negative indexing

[7 8 9]


In [8]:
print(arr[0:2]) # range selection (end value is inclusive)

[[1 2 3]
 [4 5 6]]


In [9]:
print(arr[1:]) # select all

[[4 5 6]
 [7 8 9]]


In [10]:
print(arr[0:3:2]) # step selection

[[1 2 3]
 [7 8 9]]


In [11]:
print(arr[:, 0]) # column at index 0

[1 4 7]


In [12]:
print(arr[:, 1:2])

[[2]
 [5]
 [8]]


In [13]:
print(arr[:, :2]) # steps column

[[1 2]
 [4 5]
 [7 8]]


### `3D` array *Slicing*

In [14]:
arr = np.array([
    [[1, 2, 3],[4, 5, 6]],
    [[7, 8, 9],[10, 11, 12]]
])

#### slice operator **`arr[start:stop:step, start:stop:step, start:stop:step]`**

In [15]:
print(arr[0]) # select block at index 0

[[1 2 3]
 [4 5 6]]


In [16]:
print(arr[:,1,:]) # select specific row 

[[ 4  5  6]
 [10 11 12]]


In [17]:
print(arr[:,:,0]) # select specific columns

[[ 1  4]
 [ 7 10]]


In [18]:
print(arr[:, 0:1, :]) # select first row

[[[1 2 3]]

 [[7 8 9]]]


In [19]:
print(arr[:,:,1:2]) # select second columns

[[[ 2]
  [ 5]]

 [[ 8]
  [11]]]


#### think : **`arr[blocks, rows, columns]`**