# **Broadcasting** in `NumPy`

#### `Broadcasting` allows NumPy to preform arithmetic operations on arrays with ***different shape***, without manually reshaping and copying data.

## **`Broadcasting Rules`**
#### NumPy compares dimensions from right to left
#### Two Dimensions are compatible if:
*   1. They are equal
*   2. One of the dimensions has a size of 1
*   3. One dimension doesn't exists

In [1]:
import numpy as np

In [2]:
array1 = np.array([[1,2,3,4]])
array2 = np.array([[1],[2],[3],[4]])

In [3]:
print(array1.shape)
print(array2.shape)

(1, 4)
(4, 1)


#### compare from right to left, here 4 and 1, 
#### According to the Broadcasting rule, dimension should be equal or one dimension should be equal to 1, thus they are compatible.

In [4]:
print(array1 * array2)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


#### here we virtually expand the array

In [5]:
array1 = np.array([
        [1,2,3,4],
        [5,6,7,8]
        ])
array2 = np.array([[1],[2],[3],[4]])

In [6]:
print(array1.shape)
print(array2.shape)

(2, 4)
(4, 1)


#### Here while comparing we get 2 and 4, according to the broadcasting rule, dimension should be equal or 1 but here they are different. Thus they `can't be broadcast together`.

In [8]:
# print(array1 * array2) # ValueError: operands could not be broadcast together with shapes (2,4) (4,1) 

In [9]:
array1 = np.array([
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12],
        [13,14,15,16]
        ])
array2 = np.array([[1],[2],[3],[4]])

In [10]:
print(array1.shape)
print(array2.shape)

(4, 4)
(4, 1)


In [11]:
print(array1 + array2)

[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]]
