# Array ***Arithmetic*** in `NumPy`

#### `NumPy` allows you to perform arithmetic operations element-by-element on arrays.

In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,4,5])

## `Scalar` Arithmetic

#### Performing the array arithmetic operation between a NumPy array and a single value(scalar).

In [3]:
# Addition
print(array + 5)

[ 6  7  8  9 10]


In [4]:
# Subtraction
print(array - 5)

[-4 -3 -2 -1  0]


In [5]:
# Multiplication
print(array * 5)

[ 5 10 15 20 25]


In [7]:
# Division 
print(array / 5)

[0.2 0.4 0.6 0.8 1. ]


In [9]:
# Floor division 
print(array // 2)

[0 1 1 2 2]


In [10]:
# Power 
print(array ** 2)

[ 1  4  9 16 25]
