# **Vectorized** Math *fn* in `NumPy`

#### Vectorized Math Functions in NumPy allows us to **perform mathematical operation** on an entire array without using the `for loops`


|**Function**|**description**|
|---|---|
|`np.sqrt()`|*square root*|
|`np.square()`|*square*|
|`np.abs()`|*absolute*|
|`np.exp()`|*exponent*|
|`np.log()`|*logarithmic (Natural)*|
|`np.log10()`|*logarithmic (base-10)*|
|`np.sin()`|*Sine*|
|`np.cos()`|*Cosine*|
|`np.tan()`|*Tangent*|
|`np.ceil()`|*round-up*|
|`np.floor()`|*round-down*|
|`np.round()`|*round value*|


In [2]:
import numpy as np

In [3]:
array = np.array([1, 4, 9, 16])

#### 1. `np.sqrt()`

In [4]:
print(np.sqrt(array))

[1. 2. 3. 4.]


2. `np.square()`

In [5]:
print(np.square(array))

[  1  16  81 256]


In [6]:
array = np.array([-2.5, 3.2, -4.7, 5.8])

#### 3. `np.abs()`

In [7]:
print(np.abs(array))

[2.5 3.2 4.7 5.8]


#### 4. `np.ceil()`

In [8]:
print(np.ceil(array))

[-2.  4. -4.  6.]


#### 5. `np.floor`

In [9]:
print(np.floor(array))

[-3.  3. -5.  5.]


#### 6. `np.floor()`

In [10]:
print(np.floor(array))

[-3.  3. -5.  5.]
